{
  imports = [
    ./anki.nix
    ./auth.nix
    ./containers.nix
    ./esphome.nix
    ./hermes.nix
    ./homepage.nix
    ./immich.nix
    ./lldap.nix
    ./matrix.nix
    ./monitoring.nix
    ./nameserver.nix
    ./onerep.nix
    ./rss.nix
    ./smarthome.nix
    ./valheim.nix
    ./vikunja.nix
    ./wireguard.nix
  ];
}
