---
name: Check flake

"on":
  push:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Workaround for broken check
        run: |
          nix eval --json .#nixosConfigurations.nasgul.config.services.dashy.package
          nix eval --json .#iproute2

      - name: Check flake
        run: |
          nix flake check --no-build
