---
name: Check flake

"on":
  push:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v18
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Workaround for broken check
        run: |
          nix show-derivation .#dashy
      - name: Check flake
        run: |
          nix flake check --no-build
