---
name: Check flake

"on":
  - pull_request
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install nix
        uses: cachix/install-nix-action@v18
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check flake
        run: |
          # Build playground as workaround
          # (deploy-rs checks output does not pass otherwise)
          nix build .#nixosConfigurations.playground.config.system.build.toplevel
          nix flake check --no-build
