---
name: Check flake

"on":
  push:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            substituters = https://helix.cachix.org/ https://cache.nixos.org/ 
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= helix.cachix.org-1:ejp9KQpR1FBI2onstMQ34yogDm4OgU2ru6lIwPvuCVs=

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Workaround for broken check
        run: |
          nix eval --json .#nixosConfigurations.nasgul.config.services.dashy.package
          nix eval --json .#iproute2

      - name: Check flake
        run: |
          nix flake check --no-build
