# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "mpt3sas" "sd_mod" ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems = {
    "/" = {
      device = "rpool/root";
      fsType = "zfs";
    };
    "/nix" = {
      device = "rpool/root/nix";
      fsType = "zfs";
    };
    "/var" = {
      device = "rpool/root/var";
      fsType = "zfs";
    };
    "/var/tmp" = {
      device = "rpool/root/var/tmp";
      fsType = "zfs";
    };
    "/home" = {
      device = "rpool/root/home";
      fsType = "zfs";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/EC83-EFDC";
      fsType = "vfat";
    };
    "/boot-fallback" = {
      device = "/dev/disk/by-uuid/EC84-4BF0";
      fsType = "vfat";
    };
    "/chonk" = {
      device = "chonk";
      fsType = "zfs";
    };
    "/chonk/media" = {
      device = "chonk/media";
      fsType = "zfs";
    };
    "/chonk/database" = {
      device = "chonk/database";
      fsType = "zfs";
    };
    "/chonk/nextcloud" = {
      device = "chonk/nextcloud";
      fsType = "zfs";
    };
    "/chonk/repositories" = {
      device = "chonk/repositories";
      fsType = "zfs";
    };
    "/chonk/share" = {
      device = "chonk/share";
      fsType = "zfs";
    };
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wg1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
